<?php

namespace Prof\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{
    public function getetudiants($id)
    {

        $query = $this->createQueryBuilder('e')
            ->where('e.professeur = :id')
            ->setParameter('id', $id)
            ->getQuery();
        $e=$query-> getresult();
        return $e;
    }
}
