<?php

namespace Prof\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurRepository extends EntityRepository
{
    public function getprofbyemail($email)
    {

        $query = $this->createQueryBuilder('e')
            ->where('e.Email= :email')
            ->setParameter('email', $email+'@gmail.com')
            ->getQuery();
        $e=$query-> getresult();
        return $e;
    }
}
